Telehakim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


app_name = 'telehakim'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls')),
    path('chat/', include('webrtc.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('recommend/', include('dr_re.urls'), name="recommend"),
    path('appointment/', include('appointment.urls')),
    path('', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Tenalink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


app_name = 'tenalink'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('webrtc.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('recommend/', include('recommendation.urls'), name="recommend"),
    path('appointment/', include('appointment.urls')),
    path('', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path
from account.views import *

app_name = 'account'
urlpatterns = [
    path('login/', login, name="login"),
    path('', home_page, name="home_page"),
    path('forgot_password/', forgot_password, name="revoke-new-password"),
    path('register_patient/<str:_to>/', register_patient, name="register-patient"),
    path('register_doctor/<str:_from>/', register_doctor, name="register-doctor"),
    path('delete/<str:pk>/<str:role>/', delete_user, name="delete-user"),
    path('update_password/<str:pk>/<str:role>', update_password, name='update_password'),
    path('update_password_forgot/<str:pk>/<str:role>/', update_password_forgot, name='update_password_forgot'),
    path('logout/', logout, name="logout"),
]

dr_re/urls.py
from django.urls import path
from dr_re.views import *

urlpatterns = [
    path("", re_home, name="re_home"),
    path("test", test_page, name="test"),
    path("login", login, name="login"),
    path("interview0", interview0, name="interview0"),
    path("interview1", interview1, name="interview1"),
    path("interview2", interview2, name="interview2"),
    path("interview3", interview3, name="interview3"),
    path("interview4", interview4, name="interview4"),
    path("vom_interview", vom_interview, name="vom_interview"),

    # cough
    path('cough_interview1', cough_interview1, name="cough_interview1"),
    path('cough_interview2', cough_interview2, name="cough_interview2"),
    path('cough_result', cough_result, name='cough_result'),

    # headache
    path("headache_interview1", headache_interview1, name='headache_interview1'),
    path("headache_interview2", headache_interview2, name='headache_interview2'),
    path("headache_interview3", headache_interview3, name='headache_interview3'),
    path("headache_interview4", headache_interview4, name='headache_interview4'),
    path("headache_interview5", headache_interview5, name='headache_interview5'),
    path("headache_result", headache_result, name="headache_result"),
    # fever
    path("fever_interview1", fever_interview1, name='fever_interview1'),
    path("fever_interview2", fever_interview2, name='fever_interview2'),
    path("fever_interview3", fever_interview3, name='fever_interview3'),
    path("fever_interview4", fever_interview4, name='fever_interview4'),
    path("fever_interview5", fever_interview5, name='fever_interview5'),
    path("fever_result", fever_result, name='fever_result'),
    path("recommend", recommend, name='recommend'),
]

templates/tenalink/index_base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %} {% endblock %}| Tenalink</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link href="{% static 'asset/assets/image.png' %}" rel="icon">
    <!-- Favicons -->
    <link href="{% static 'assets/img/post.jpg' %}" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/VERSION/css/font-awesome.min.css">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">

      <a href="#" class="logo d-flex align-items-center me-auto">
        <img src="{% static 'land/assets/images/logo-full.svg' %}" alt="" width="100" height="50">
      </a>

      <nav id="navmenu" class="navmenu">

        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

      <a class="btn-getstarted" href="{% url 'account:home_page'%}">Home</a>

    </div>
  </header>
<body class="toggle-sidebar" onload="post_none()">
<div class="page-wrapper ">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS or message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <div class="custom-modal">
                <div class="succes succes-animation icon-top"><i class="bi bi-check2"></i></div>

                <div class="content">
                    <p class="message-type text-center small text-success">{{ message }}</p>
                </div>
            </div>
            {% else %}
            <div class="custom-modal">
                <div class="danger danger-animation icon-top"><i class="bi bi-x-lg"></i></div>
                <div class="content">
                    <p class="message-type text-danger">{{ message }}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>


<main id="main" class="main">


    <section class="section">
        {% block middle %}

        {% endblock %}
    </section>
<script>
    function post_none(){
        setTimeout( function (){
            var cm = document.getElementsByClassName('custom-modal')[0];
            cm.classList.add('post_none');
        }, 2000);
    }
</script>
</main><!-- End #main -->



<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>

<script src="{% static 'assets/js/main.js' %}"></script>


</body>

</html>

templates/tenalink/main_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %} {% endblock %}-Dashboard </title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <link href="{% static 'asset/assets/image.png' %}" rel="icon">
    <!-- Favicons -->
    <link href="{% static 'assets/img/post.jpg' %}" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<body onload="post_none()">
{# start of pop up message #}
<div class="page-wrapper ">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS or message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                <div class="custom-modal">
                    <div class="succes succes-animation icon-top"><i class="bi bi-check2"></i></div>

                    <div class="content">
                        <p class="message-type text-center small text-success">{{ message }}</p>
                    </div>
                </div>
            {% else %}
                <div class="custom-modal">
                    <div class="danger danger-animation icon-top"><i class="bi bi-x-lg"></i></div>
                    <div class="content">
                        <p class="message-type text-danger">{{ message }}</p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
{# end of pop up message #}
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="#" class="logo d-flex align-items-center">
            <img src="{% static 'land/assets/images/logo-new.svg' %}" alt="">
            <span class="d-none d-lg-block">Tenalink</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->
    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->

            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    {% if notifications|length != 0 %}
                        <span class="badge bg-primary badge-number">{{ notifications|length }}</span>
                    {% endif %}
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        You have {{ notifications|length }} new notifications
                        {% if notify|length != 0 %}
<!--                            <a href="{% url 'all-or-one-to-seen' 'none' %}"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>-->
                        {% endif %}
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    {% for notification in notifications %}
                        <li class="notification-item">
                            <i class="bi bi-info-circle text-primary"></i>
                            <div>
                                <h4>
                                    Hi Dr. {{ user.first_name }}, <br><br>

                                    You have schedule today with <b>{{ notification.patient.first_name }} </b>that starts in less than 30 minutes.
                                    <br>

                                </h4>
                                <p> Teenassist <b>mail@tenalink.et</b> or call
                                    +251949257378 </p>
                            </div>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    {% endfor %}
                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->


            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <img src="{{ user.photo.url }}" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.first_name|title }}. {{ user.last_name|first|capfirst }}</span>
                </a><!-- End Profile Image Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>{{ user.first_name|title }} {{ user.last_name|title }}</h6>
                        <span>
                            {{ user_role|title }}
                            {% if user.is_verified %}
                                <span class="badge bg-success rounded-pill">Verified</span>
                            {% elif user_role == 'doctor' %}
                                <span class="badge bg-danger rounded-pill">Not Verified</span>
                            {% endif %}
                        </span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                           href="/dashboard/{{user_role}}/?pages=profile">
                            <i class="bi bi-person"></i>
                            <span>My Profile</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                           href="/dashboard/{{ user_role }}/?pages=profile">
                            <i class="bi bi-gear"></i>
                            <span>Account Settings</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% url 'account:logout' %}">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Sign Out</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->
</header>
<aside id="sidebar" class="sidebar">
    {% block aside %}

    {% endblock %}
</aside>
<main id="main" class="main">

    <section class="section">
        {% block middle %}{% endblock %}
    </section>
    <script>
        function post_none() {
            setTimeout(function () {
                var cm = document.getElementsByClassName('custom-modal')[0];
                cm.classList.add('post_none');
            }, 2000);
        }
    </script>
</main><!-- End #main -->

<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright 2024<strong><span>Tenalink</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>

<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/tenalink/register_doctor.html
{% extends 'tenalink/index_base.html' %}

{% block title %}
Register
{% endblock %}

{% block breadcrumb %}
    doctor_register
{% endblock %}

{% block middle %}
    {% include 'tenalink/partials/doctor_form.html' %}
{% endblock %}

templates/tenalink/register_patient.html
{% extends 'tenalink/index_base.html' %}

{% block title %}
Register
{% endblock %}

{% block breadcrumb %}
patient
{% endblock %}

{% block middle %}
    {% include 'tenalink/partials/patient_form.html' %}
{% endblock %}