Telehakim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


app_name = 'telehakim'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls')),
    path('chat/', include('webrtc.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('recommend/', include('dr_re.urls'), name="recommend"),
    path('appointment/', include('appointment.urls')),
    path('', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Tenalink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


app_name = 'tenalink'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('webrtc.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('recommend/', include('recommendation.urls'), name="recommend"),
    path('appointment/', include('appointment.urls')),
    path('', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path
from account.views import *

app_name = 'account'
urlpatterns = [
    path('login/', login, name="login"),
    path('', home_page, name="home_page"),
    path('forgot_password/', forgot_password, name="revoke-new-password"),
    path('register_patient/<str:_to>/', register_patient, name="register-patient"),
    path('register_doctor/<str:_from>/', register_doctor, name="register-doctor"),
    path('delete/<str:pk>/<str:role>/', delete_user, name="delete-user"),
    path('update_password/<str:pk>/<str:role>', update_password, name='update_password'),
    path('update_password_forgot/<str:pk>/<str:role>/', update_password_forgot, name='update_password_forgot'),
    path('logout/', logout, name="logout"),
]

dr_re/urls.py
from django.urls import path
from dr_re.views import *

urlpatterns = [
    path("", re_home, name="re_home"),
    path("test", test_page, name="test"),
    path("login", login, name="login"),
    path("interview0", interview0, name="interview0"),
    path("interview1", interview1, name="interview1"),
    path("interview2", interview2, name="interview2"),
    path("interview3", interview3, name="interview3"),
    path("interview4", interview4, name="interview4"),
    path("vom_interview", vom_interview, name="vom_interview"),

    # cough
    path('cough_interview1', cough_interview1, name="cough_interview1"),
    path('cough_interview2', cough_interview2, name="cough_interview2"),
    path('cough_result', cough_result, name='cough_result'),

    # headache
    path("headache_interview1", headache_interview1, name='headache_interview1'),
    path("headache_interview2", headache_interview2, name='headache_interview2'),
    path("headache_interview3", headache_interview3, name='headache_interview3'),
    path("headache_interview4", headache_interview4, name='headache_interview4'),
    path("headache_interview5", headache_interview5, name='headache_interview5'),
    path("headache_result", headache_result, name="headache_result"),
    # fever
    path("fever_interview1", fever_interview1, name='fever_interview1'),
    path("fever_interview2", fever_interview2, name='fever_interview2'),
    path("fever_interview3", fever_interview3, name='fever_interview3'),
    path("fever_interview4", fever_interview4, name='fever_interview4'),
    path("fever_interview5", fever_interview5, name='fever_interview5'),
    path("fever_result", fever_result, name='fever_result'),
    path("recommend", recommend, name='recommend'),
]

templates/telehakim/index_base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %} {% endblock %}| TeleHakim</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/post.jpg' %}" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<body class="toggle-sidebar" onload="post_none()">
<div class="page-wrapper ">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS or message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <div class="custom-modal">
                <div class="succes succes-animation icon-top"><i class="bi bi-check2"></i></div>

                <div class="content">
                    <p class="message-type text-center small text-success">{{ message }}</p>
                </div>
            </div>
            {% else %}
            <div class="custom-modal">
                <div class="danger danger-animation icon-top"><i class="bi bi-x-lg"></i></div>
                <div class="content">
                    <p class="message-type text-danger">{{ message }}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
<!-- ======= Header ======= -->
<!--<header id="header" class="header fixed-top d-flex align-items-center">-->

<!--    <div class="d-flex align-items-center justify-content-between">-->
<!--        <a href="#" class="logo d-flex align-items-center">-->
<!--            <img src="{% static 'assets/img/post.jpg' %}" alt="">-->
<!--            <span class="d-none d-lg-block">TELEHAKIM</span>-->
<!--        </a>-->
<!--    </div>&lt;!&ndash; End Logo &ndash;&gt;-->
<!--    <nav class="header-nav ms-auto pe-3">-->
<!--        <a href="{% url 'account:login' %}" class="btn  btn-outline-dark">Login</a>-->
<!--        <a href="{% url 'account:register-patient' 'index'%}" class="btn  btn-outline-success" title="For patient use only.">Register</a>-->
<!--        <a href="{% url 'account:register-doctor' 'index'%}" class="btn  btn-outline-warning" title="For doctor use only.">Register(Dr.)</a>-->
<!--    </nav>&lt;!&ndash; End Icons Navigation &ndash;&gt;-->

<!--</header>&lt;!&ndash; End Header &ndash;&gt;-->

<main id="main" class="main">

<!--    <div class="pagetitle">-->
<!--        <h1>Wel-Come Page</h1>-->
<!--        <nav>-->
<!--            <ol class="breadcrumb">-->
<!--                <li class="breadcrumb-item"><a href=" url 'post:index-view'">Home</a></li>-->
<!--                <li class="breadcrumb-item active">{% block breadcrumb %} {% endblock %}</li>-->
<!--            </ol>-->
<!--        </nav>-->
<!--    </div>&lt;!&ndash; End Page Title &ndash;&gt;-->

    <section class="section">
        {% block middle %}

        {% endblock %}
    </section>
<script>
    function post_none(){
        setTimeout( function (){
            var cm = document.getElementsByClassName('custom-modal')[0];
            cm.classList.add('post_none');
        }, 2000);
    }
</script>
</main><!-- End #main -->

<!-- ======= Footer ======= -->
<!--<footer id="footer" class="footer">-->
<!--    <div class="copyright">-->
<!--        &copy; Copyright <strong><span>TeleHakim System.</span></strong>. All Rights Reserved-->
<!--    </div>-->
<!--    <div class="credits">-->
<!--    </div>-->
<!--</footer>&lt;!&ndash; End Footer &ndash;&gt;-->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>

<script src="{% static 'assets/js/main.js' %}"></script>


</body>

</html>

templates/telehakim/login.html
{% extends 'telehakim/index_base.html' %}

{% block title %}
Login
{% endblock %}

{% block breadcrumb %}
login
{% endblock %}

{% block middle %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
        <div class="card mb-3">
            <div class="card-body">
                <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    <p class="text-center small">Enter your email & password to login</p>
                </div>
                {% if revoke == "email" %}
                <form method="post" action="" class="row g-3 needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="col-12">
                        <label for="yourUsername" class="form-label">Email</label>
                        <div class="input-group has-validation">
                            <span class="input-group-text" id="inputGroupPrepend">@</span>
                            <input type="email" name="email" class="form-control" id="yourUsername"
                                   placeholder="please enter your email" required>
                            <div class="invalid-feedback">Your email is used to send a code.</div>
                        </div>
                    </div>

                    <div class="col-12">
                        <button class="btn btn-primary w-100" name="email_field" type="submit">Submit</button>
                    </div>
                    <div class="col-12">
                        <p class="small mb-0">Don't have account? <a
                                href="{% url 'account:register-patient' 'index' %}">Create
                            an account</a></p>
                    </div>
                </form>
                {% elif revoke == "code" %}
                <form method="post" action="" class="row g-3 needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="col-12">
                        <label for="yourUsername" class="form-label">Code</label>
                        <div class="input-group has-validation">
                            <input type="text" name="codechar" class="form-control" id="yourUsername"
                                   placeholder="Enter the code you received" required>
                            <div class="invalid-feedback">Check your email and finish the process.</div>
                        </div>
                    </div>
                    <div class="col-12">
                        <button class="btn btn-primary w-100" name="code" type="submit">Revoke</button>
                    </div>
                    <div class="col-12">
                        <p class="small mb-0">Don't have account? <a
                                href="{% url 'account:register-patient' 'index' %}">Create
                            an account</a></p>
                    </div>
                </form>
                {% elif revoke == "password" %}
                <div class="">
                    <form method="post" action="{% url 'account:update_password_forgot' id reset_req %}">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <div class="col-md-12 mb-3">
                                <input name="new_password" type="password" class="form-control"
                                       placeholder="New Password" minlength="4" required>
                            </div>

                            <div class="col-md-12 col-lg-12 mb-3">
                                <input name="renew_password" type="password" class="form-control"
                                       placeholder="Re-enter New Password" minlength="4" required>
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" name="password_update" class="btn btn-primary">Change
                                Password
                            </button>
                        </div>
                    </form>

                </div>
                {% else %}
                <form method="post" action="" class="row g-3 needs-validation" novalidate>
                    {% csrf_token %}

                    <div class="col-12">
                        <label for="yourName" class="form-label">Your Email</label>
                        <input type="email" name="email" class="form-control" id="yourName" required>
                        <div class="invalid-feedback">Please, enter your valid email!</div>
                    </div>

                    <div class="col-12">
                        <label for="yourPassword" class="form-label">Password</label>
                        <input type="password" name="password" class="form-control" id="yourPassword" minlength="4" required>
                        <div class="invalid-feedback">Please enter your password and more than 4 chars!</div>
                    </div>
                    <div class="col-12">
                        <input class="form-check-input" name="is_doctor" type="checkbox" id="gridCheck1" value="True">
                        <label class="form-check-label" for="gridCheck1">
                            Login as a Doctor
                        </label>
                    </div>
                    <div class="col-12">
                        <p class="small mb-0"><a href="{% url 'account:revoke-new-password' %}?revoke=true">I
                            forgot my password.</a>
                        </p>
                    </div>
                    <div class="col-12">
                        <button class="btn btn-primary w-100" name="login" type="submit">Login</button>
                    </div>
                    <div class="col-12">
                        <p class="small mb-0">Don't have account? <a
                                href="{% url 'account:register-patient' 'index' %}">Create
                            an account</a></p>
                        <span class="small mb-0"> <a
                                href="{% url 'account:home_page'%}">go back to home?</a></span>
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/telehakim/register_doctor.html
{% extends 'telehakim/index_base.html' %}

{% block title %}
Register
{% endblock %}

{% block breadcrumb %}
    doctor_register
{% endblock %}

{% block middle %}
    {% include 'telehakim/partials/doctor_form.html' %}
{% endblock %}

templates/telehakim/register_patient.html
{% extends 'telehakim/index_base.html' %}

{% block title %}
Register
{% endblock %}

{% block breadcrumb %}
patient
{% endblock %}

{% block middle %}
    {% include 'telehakim/partials/patient_form.html' %}
{% endblock %}