Telehakim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


app_name = 'telehakim'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls')),
    path('chat/', include('webrtc.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('recommend/', include('dr_re.urls'), name="recommend"),
    path('appointment/', include('appointment.urls')),
    path('', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Tenalink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


app_name = 'tenalink'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('webrtc.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('recommend/', include('recommendation.urls'), name="recommend"),
    path('appointment/', include('appointment.urls')),
    path('', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path
from account.views import *

app_name = 'account'
urlpatterns = [
    path('login/', login, name="login"),
    path('', home_page, name="home_page"),
    path('forgot_password/', forgot_password, name="revoke-new-password"),
    path('register_patient/<str:_to>/', register_patient, name="register-patient"),
    path('register_doctor/<str:_from>/', register_doctor, name="register-doctor"),
    path('delete/<str:pk>/<str:role>/', delete_user, name="delete-user"),
    path('update_password/<str:pk>/<str:role>', update_password, name='update_password'),
    path('update_password_forgot/<str:pk>/<str:role>/', update_password_forgot, name='update_password_forgot'),
    path('logout/', logout, name="logout"),
]

dr_re/urls.py
from django.urls import path
from dr_re.views import *

urlpatterns = [
    path("", re_home, name="re_home"),
    path("test", test_page, name="test"),
    path("login", login, name="login"),
    path("interview0", interview0, name="interview0"),
    path("interview1", interview1, name="interview1"),
    path("interview2", interview2, name="interview2"),
    path("interview3", interview3, name="interview3"),
    path("interview4", interview4, name="interview4"),
    path("vom_interview", vom_interview, name="vom_interview"),

    # cough
    path('cough_interview1', cough_interview1, name="cough_interview1"),
    path('cough_interview2', cough_interview2, name="cough_interview2"),
    path('cough_result', cough_result, name='cough_result'),

    # headache
    path("headache_interview1", headache_interview1, name='headache_interview1'),
    path("headache_interview2", headache_interview2, name='headache_interview2'),
    path("headache_interview3", headache_interview3, name='headache_interview3'),
    path("headache_interview4", headache_interview4, name='headache_interview4'),
    path("headache_interview5", headache_interview5, name='headache_interview5'),
    path("headache_result", headache_result, name="headache_result"),
    # fever
    path("fever_interview1", fever_interview1, name='fever_interview1'),
    path("fever_interview2", fever_interview2, name='fever_interview2'),
    path("fever_interview3", fever_interview3, name='fever_interview3'),
    path("fever_interview4", fever_interview4, name='fever_interview4'),
    path("fever_interview5", fever_interview5, name='fever_interview5'),
    path("fever_result", fever_result, name='fever_result'),
    path("recommend", recommend, name='recommend'),
]

templates/telehakim/partials/profile.html
<div class="row">
    <div class="col-xl-4">
        <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                <img src="{{ user.photo.url }}" alt="Profile" class="rounded-circle" width="200" height="200">
                <h2>{{ user.first_name|title }} {{ user.last_name|title }}</h2>
                <h3>
                    {{user_role|title}}
                    {% if user.is_verified %}
                        <span class="badge bg-success rounded-pill">Verified</span>
                    {% elif user_role == 'doctor' %}
                        <span class="badge bg-danger rounded-pill">Not Verified</span>
                    {% endif %}
                </h3>
            </div>
        </div>
    </div>

    <div class="col-xl-8">

        <div class="card">
            <div class="card-body pt-3">
                <ul class="nav nav-tabs nav-tabs-bordered">
                    <li class="nav-item">
                        <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">
                            Overview
                        </button>
                    </li>
                    <li class="nav-item">
                        <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit"
                                onclick="blur_password()">Edit
                            Profile
                        </button>
                    </li>
                    <li class="nav-item">
                        <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">
                            Change Password
                        </button>
                    </li>
                </ul>
                <div class="tab-content pt-2">

                    <div class="tab-pane fade show active profile-overview" id="profile-overview">

                        <h5 class="card-title">Profile Details</h5>

                        <div class="row">
                            <div class="col-lg-3 col-md-4 label ">Full Name</div>
                            <div class="col-lg-9 col-md-8">{{ user.first_name|title }} {{ user.last_name|title }}</div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-4 label">Company</div>
                            <div class="col-lg-9 col-md-8">Telehakim Service company</div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-4 label">Job</div>
                            <div class="col-lg-9 col-md-8">{{ user_role|title}}</div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-4 label">Address</div>
                            <div class="col-lg-9 col-md-8">{{ user.address }}</div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-4 label">Phone</div>
                            <div class="col-lg-9 col-md-8">{{ user.phone }}</div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-4 label">Email</div>
                            <div class="col-lg-9 col-md-8">{{ user.email }}</div>
                        </div>
                    </div>

                    <div class="tab-pane fade profile-edit pt-3" id="profile-edit">


                        <form method="post" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for form in update_form %}
                                {% if forloop.counter0 == 4 %}
                                <div class="row mb-3">
                                    <div class="col-md-8 col-lg-9">
                                        <input type="text" id="id_password" name="password"
                                               class="form-control">
                                    </div>
                                </div>
                                {% else %}
                                <div class="row mb-3">
                                    <label for="{{ form.id_for_label }}"
                                           class="col-md-4 col-lg-3 col-form-label">{{ form.label }}</label>
                                    <div class="col-md-8 col-lg-9">
                                        {{ form }}
                                    </div>
                                </div>
                                {% endif %}
                            {% endfor %}

                            <div class="text-center">
                                <input name="update" type="submit" class="btn btn-primary" value="Save Changes">
                            </div>
                        </form>
                    </div>
                    <script>
                            function blur_password() {
                                let pass = document.getElementById('id_password')
                                pass.removeAttribute('required')
                                pass.setAttribute('type', 'hidden')
                                pass.value = "{{user.password}}"
                            }
                    </script>
                    <div class="tab-pane fade pt-3" id="profile-change-password">
                        <form method="post" action="{% url 'account:update_password' user.id user_role%}">
                            {% csrf_token %}
                            <div class="row mb-3">
                                <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current
                                    Password</label>
                                <div class="col-md-8 col-lg-9">
                                    <input name="current_password" type="password" class="form-control"
                                           id="currentPassword" minlength="4" required>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New
                                    Password</label>
                                <div class="col-md-8 col-lg-9">
                                    <input name="new_password" type="password" class="form-control"
                                           id="newPassword" minlength="4" required>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="renew_password" class="col-md-4 col-lg-3 col-form-label">Re-enter
                                    New
                                    Password</label>
                                <div class="col-md-8 col-lg-9">
                                    <input name="renew_password" type="password" class="form-control"
                                           id="renew_password" required>
                                </div>
                            </div>

                            <div class="text-center">
                                <button type="submit" name="password_update" class="btn btn-primary">Change
                                    Password
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>